version: "3.8"
services:
  configuration:
    container_name: module-configuration
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:21-jre-alpine-3.22
        COPY ./module-configuration/target/*.jar app.jar
        RUN apk add --no-cache curl
        EXPOSE 8888
        ENTRYPOINT ["java", "-jar", "app.jar"]
    environment:
      PORT_SERVICE: 8888
    ports:
      - "8888:8888"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 24h
      start_period: 25s
      start_interval: 5s
    networks:
      - booking-network

  discovery:
    container_name: discovery-service
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:21-jre-alpine-3.22
        COPY ./module-discovery/target/*.jar app.jar
        RUN apk add --no-cache curl
        EXPOSE 8761
        ENTRYPOINT ["java", "-jar", "app.jar"]
    ports:
      - "8761:8761"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 24h
      start_period: 25s
      start_interval: 5s
    networks:
      - booking-network

  booking:
    container_name: booking-service
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:21-jre-alpine-3.22
        COPY ./module-booking/target/*.jar app.jar
        RUN apk add --no-cache curl
        EXPOSE 8081
        ENTRYPOINT ["java", "-jar", "app.jar"]
    ports:
      - "8081:8081"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://booking-service:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configuration:
        condition: service_healthy
      discovery:
        condition: service_healthy
    networks:
      - booking-network

  hotel_management:
    container_name: hotel-management-service
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:21-jre-alpine-3.22
        COPY ./module-hotel-management/target/*.jar app.jar
        RUN apk add --no-cache curl
        EXPOSE 8082
        ENTRYPOINT ["java", "-jar", "app.jar"]
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://hotel-management-service:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configuration:
        condition: service_healthy
      discovery:
        condition: service_healthy
    networks:
      - booking-network

  gateway:
    container_name: gateway-service
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:21-jre-alpine-3.22
        COPY ./module-gateway/target/*.jar app.jar
        RUN apk add --no-cache curl
        EXPOSE 8080
        ENTRYPOINT ["java", "-jar", "app.jar"]
    depends_on:
      configuration:
        condition: service_healthy
      booking:
        condition: service_healthy
      hotel_management:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - booking-network

networks:
  booking-network:
    driver: bridge
