spring:
  application:
    name: module-hotel-management
  cloud:
    config:
      enabled: true
      uri: module-hotel-management.yml
  config:
    import: configserver:http://module-configuration:8888/