spring:
  application:
    name: module-hotel-management
  cloud:
    config:
      enabled: true
      uri: module-hotel-management.yml
  config:
    import: configserver:http://module-configuration:8888/

#server:
#  port: 8082
#spring:
#  cloud:
#    config:
#      enabled: false
#  application:
#    name: module-booking
#  datasource:
#    url: jdbc:h2:mem:booking_db
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false
#  jpa:
#    open-in-view: on
#    show-sql: on
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#
#security:
#  token:
#    signing:
#      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
#    expiration:
#      milliseconds: 144000000