INSERT INTO HOTELS (ID, NAME) VALUES(1, 'Общага');

INSERT INTO ROOMS (ID, NUMBER, HOTEL_ID, TIMES_BOOKED) VALUES(1, '313', 1, 0);
INSERT INTO ROOMS (ID, NUMBER, HOTEL_ID, TIMES_BOOKED) VALUES(2, '314', 1, 0);