server:
  port: 8081
spring:
  application:
    name: module-booking
  datasource:
    url: jdbc:h2:mem:booking_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    open-in-view: on
    show-sql: on
