server:
  port: 8080
spring:
  application:
    name: module-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: module-booking
              uri: http://booking-service:8081
              predicates:
                - Path=/api/users,/api/users/user,/api/users/user/{id},/registration
            - id: module-hotel-management
              uri: http://hotel-management-service:8082
              predicates:
                - Path=/users,/users/{id},/hotels,/hotels/{id}

#          filters:
#            - JwtAuthFilter