server:
  port: 8080
spring:
  application:
    name: module-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: module-booking
              uri: http://module-booking:8081
              predicates:
                - Path=/api/auth/sign/up,/api/auth/sign/in,/api/users,/api/users/user,/api/users/user/{id},/api/bookings,/api/bookings/booking,/api/bookings/booking/{id}
            - id: module-hotel-management
              uri: http://module-hotel-management:8082
              predicates:
                - Path=/api/hotels,/api/hotels/hotel,/api/hotels/hotel/{id},/api/rooms,/api/rooms/room,/api/rooms/room/{id}
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    urls:
      - name: module-booking
        url: /bookings/v3/api-docs
      - name: module-hotel-management
        url: /hotels/v3/api-docs