server:
  port: 8080
spring:
  application:
    name: module-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: module-booking
              uri: http://module-booking:8081
              predicates:
                - Path=/api/auth/sign/up,/api/auth/sign/in,/api/users,/api/users/user,/api/users/user/{id},/api/bookings,/api/bookings/booking,/api/bookings/booking/{id}
            - id: module-hotel-management
              uri: http://module-hotel-management:8082
              predicates:
                - Path=/users,/users/{id},/hotels,/hotels/{id}
              filters:
                - JwtAuthFilter