spring:
  application:
    name: module-booking
  cloud:
    config:
      enabled: true
      uri: module-booking.yml
  config:
    import: configserver:http://module-configuration:8888/

#logging:
#  level:
#    root: INFO
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    fetchRegistry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    healthcheck:
#      enabled: false
#  instance:
#    preferIpAddress: false
#    metadataMap:
#      management.context-path: /
#server:
#  port: 8081
#spring:
#  cloud:
#    config:
#      enabled: false
#  application:
#    name: module-booking
#  datasource:
#    url: jdbc:h2:mem:booking_db
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false
#  jpa:
#    open-in-view: on
#    show-sql: on
#
#security:
#  token:
#    signing:
#      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
#    expiration:
#      milliseconds: 144000000