spring:
  application:
    name: module-booking
  cloud:
    config:
      enabled: true
      uri: module-booking.yml
  config:
    import: configserver:http://module-configuration:8888/

#logging:
#  level:
#    root: INFO
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    healthcheck:
#      enabled: true
#  instance:
#    preferIpAddress: true
#    metadataMap:
#      management.context-path: /
#server:
#  port: 8081
#spring:
#  cloud:
#    config:
#      enabled: false
#  application:
#    name: module-booking
#  datasource:
#    url: jdbc:h2:mem:booking_db
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false
#  jpa:
#    open-in-view: on
#    show-sql: on